GET http://localhost:8001/member/test
Accept: application/json

<> 2026-08-03T020508.200.json

###

GET http://localhost:8000/member/test
Accept: application/json

<> 2026-08-03T020508.200.json
###

GET http://localhost:8000/member/member/count
Accept: application/json
###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile =123

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
	"mobile": "15812788124"
}
###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
	"mobile": "15812788124",
	"code": "1234"
}

###

POST http://localhost:8000/member/member/count
Content-Type: application/json
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3ODYzOTQ2MDMsIm1vYmlsZSI6IjE1ODEyNzg4MTI0IiwiaWQiOjIwODQ2MzE3OTAzOTU0NjE2MzIsImV4cCI6MTc4NjQ4MTAwMywiaWF0IjoxNzg2Mzk0NjAzfQ.hZSHbddUBrvYl1QaGcRdvVT1o_x7TdNc0HtnHjs_09s"

###