GET http://localhost:8001/member/test
Accept: application/json

<> 2026-08-03T020508.200.json

###

GET http://localhost:8000/member/test
Accept: application/json

<> 2026-08-03T020508.200.json
###

GET http://localhost:8000/member/member/count
Accept: application/json
###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile =123

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
	"mobile": "15812788124"
}
###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
	"mobile": "15812788124",
	"code": "1234"
}

> {%
client.log(JSON.stringify(response.body))
client.log(JSON.stringify(response.body.content.token))
client.global.set("token", response.body.content.token)
  %}

###

GET http://localhost:8000/member/member/count
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3ODYzOTU3NTYsIm1vYmlsZSI6IjE1ODEyNzg4MTI0IiwiaWQiOjIwODQ2MzE3OTAzOTU0NjE2MzIsImV4cCI6MTc4NjQ4MjE1NiwiaWF0IjoxNzg2Mzk1NzU2fQ.bxYupQgDT0vYgufRNFqzYlzKdT_En7bqAuYxPMAb7Cs

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list
Content-Type: application/json
token: {{token}}


###
